// scripts/generate-embedded-assets.ts — E12: snapshot templates/,
// bundled/prompts/, and bundled/docs/ into a TS module so the compiled
// sidecar carries them (the repo tree is not on disk inside a bun binary).
//
// Run by scripts/build-worker.sh before compiling. The generated file is
// committed so `tsc --noEmit` works without a build step; the build always
// regenerates it, so the committed copy never goes stale in a release.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const OUT = join(ROOT, "backends", "embedded-assets.generated.ts");

function snapshotDir(dir: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const entry of readdirSync(dir, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const absolute = join(entry.parentPath, entry.name);
    const key = relative(dir, absolute).split(sep).join("/");
    files[key] = readFileSync(absolute, "utf8");
  }
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)));
}

const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as { version: string };
const templates = snapshotDir(join(ROOT, "templates"));
const prompts = snapshotDir(join(ROOT, "bundled", "prompts"));
const docs = snapshotDir(join(ROOT, "bundled", "docs"));

// pdfjs-dist worker source — needed at runtime for PDF extraction in compiled binary
const pdfWorkerPath = join(ROOT, "node_modules", "pdfjs-dist", "legacy", "build", "pdf.worker.min.mjs");
const pdfWorkerSource = readFileSync(pdfWorkerPath, "utf8");

const banner =
  "// AUTO-GENERATED by scripts/generate-embedded-assets.ts — do not edit.\n" +
  "// Snapshot of templates/, bundled/prompts/, and bundled/docs/ for the compiled sidecar (E12).\n\n";

writeFileSync(
  OUT,
  banner +
    `export const EMBEDDED_APP_VERSION = ${JSON.stringify(pkg.version)};\n\n` +
    `export const EMBEDDED_TEMPLATES: Record<string, string> = ${JSON.stringify(templates, null, 2)};\n\n` +
    `export const EMBEDDED_PROMPTS: Record<string, string> = ${JSON.stringify(prompts, null, 2)};\n\n` +
    `export const EMBEDDED_DOCS: Record<string, string> = ${JSON.stringify(docs, null, 2)};\n\n` +
    `export const EMBEDDED_PDF_WORKER: string = ${JSON.stringify(pdfWorkerSource)};\n`,
  "utf8",
);

console.log(
  `Embedded assets generated: v${pkg.version}, ${Object.keys(templates).length} template files, ${Object.keys(prompts).length} prompts, ${Object.keys(docs).length} docs`,
);
