// tests/unit/embedded-assets-sync.test.ts — the committed snapshot tells the
// truth about what is on disk.
//
// `embedded-assets.generated.ts` is regenerated by scripts/build-worker.sh, so
// a release always ships current content. Nothing regenerates it during normal
// work, though, and nothing checked it: editing `bundled/prompts/agents-base.md`
// and committing left the snapshot describing the previous wording, with the
// full gate green. Remembering to run the generator is not a rule anyone can
// disobey — it is one they can simply not think of — so it belongs here.
//
// The version field is covered separately by version-sync.test.ts
// (NFR-MIGRATE-07). `EMBEDDED_PDF_WORKER` is deliberately not compared: it
// comes from node_modules rather than from the repo, so it is not something a
// contributor edits and forgets.

import { readdirSync, readFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { describe, expect, it } from "vitest";

import {
  EMBEDDED_DOCS,
  EMBEDDED_PROMPTS,
  EMBEDDED_TEMPLATES,
} from "../../backends/embedded-assets.generated";

const ROOT = join(__dirname, "..", "..");

/** The same snapshot the generator takes: relative path → contents. */
function snapshotDir(dir: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const entry of readdirSync(dir, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const absolute = join(entry.parentPath, entry.name);
    files[relative(dir, absolute).split(sep).join("/")] = readFileSync(absolute, "utf8");
  }
  return files;
}

const CASES: [string, Record<string, string>, string[]][] = [
  ["templates", EMBEDDED_TEMPLATES, ["templates"]],
  ["prompts", EMBEDDED_PROMPTS, ["bundled", "prompts"]],
  ["docs", EMBEDDED_DOCS, ["bundled", "docs"]],
];

describe("embedded assets match the repo", () => {
  for (const [name, embedded, segments] of CASES) {
    it(`${name} on disk and in the snapshot are the same files`, () => {
      expect(Object.keys(embedded).sort()).toEqual(
        Object.keys(snapshotDir(join(ROOT, ...segments))).sort(),
      );
    });

    it(`${name} contents are identical`, () => {
      const onDisk = snapshotDir(join(ROOT, ...segments));
      const stale = Object.keys(onDisk).filter((file) => onDisk[file] !== embedded[file]);
      expect(
        stale,
        "Changed on disk but not in the committed snapshot. Run " +
          "`npx tsx scripts/generate-embedded-assets.ts` — the compiled sidecar " +
          "reads these, not the repo tree.",
      ).toEqual([]);
    });
  }
});
